name: Opensource CI

on:
  push: 
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: gradle caching
        uses: actions/cach@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{runner.os}}-gradle-${{hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')}}
          restore-keys: |
            ${{runner.os}}-gradle-

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: OPENSOURCE CI
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: 안녕하시지~
          webhook: ${{secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.SUCCESS_IMAGE }}
          descripation: 성공이시지~
          color: 00FF00
          url: "https://github.com/sarisia/actons-status-discord"
          username: 유니 CI 봇

      - name: OPENSOURCE CI
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with: 
          title: 잘 가시지~
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.FAILED_IMAGE }}
          description: 귀여우니까 욘서..?
          color: BC3639
          url: "https://github.com/sarisia/actons-status-discord"
          username: 유니 CI 봇
  
